const _ = require("lodash");

let jsRandom = Math.floor((Math.random() * 100) + 1);

let _Random = _.random(1, 100);

let combinedArray = [1, 2, 3] + [4, 5, 6];

let combined_Array = _.concat([1, 2, 3], [4, 5, 6], [7, 8, 9]);

console.log("Number generated by JS: " + jsRandom)
console.log("Number genereated by Lodash: " + _Random);

console.log(combinedArray);
console.log(combined_Array);